# Generated by Django 2.1.3 on 2018-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smart_phone_ownership', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=1, null=True, verbose_name='Do you own a Smartphone?')),
                ('smart_phone_usage', models.CharField(blank=True, choices=[('Less than one hour  day', 'Less than one hour a day'), ('1 - 2 Hours a day', '1 - 2 Hours a day'), ('2 - 4 hours a day', '2 - 4 hours a day'), ('4 - 6 hours a day', '4 - 6 hours a Day'), ('6 - 8 hours a day', '6 - 8 hours a day'), ('8 + hours a day', '8 + hours a day')], max_length=1, null=True, verbose_name='If Yes, How many hours a day do you access the Internet on it?')),
            ],
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
