# Generated by Django 2.1.3 on 2018-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20181210_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can usass statements to communicate what I would like to change about my life.'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can use wish statyresf to communicate what I would like to change about my life.'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='smart_phone_ownership',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can use wish statements to communicate what I would like to change about my life.'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='smart_phone_usage',
            field=models.CharField(blank=True, choices=[('Less than one hour  day', 'Less than one hour a day'), ('1 - 2 Hours a day', '1 - 2 Hours a day'), ('2 - 4 hours a day', '2 - 4 hours a day'), ('4 - 6 hours a day', '4 - 6 hours a Day'), ('6 - 8 hours a day', '6 - 8 hours a day'), ('8 + hours a day', '8 + hours a day')], max_length=500, null=True, verbose_name='If Yes, How many hours a day do you access the Internet on it?'),
        ),
    ]
