# Generated by Django 2.1.3 on 2018-12-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20181210_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can imagine the world differently than it is at this time.'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can convey discontent over my present situation.'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can talk about my past habits.'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can express how I do things differently than in the past.'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can assert agreement and disagreement.'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='smart_phone_ownership9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can describe my hopes and my future plans by using wish statements.'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='smart_phone_ownership2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I can communicate my regrets over mistakes I made by using wish.'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='smart_phone_ownership3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No', 'Maybe')], default=None, max_length=5, null=True, verbose_name='I am comfortable describing my feelings and emotions, particularly by using wish statements.'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='smart_phone_usage',
            field=models.CharField(blank=True, choices=[('Clueless', 'Clueless'), ('Absolutely Baffled', 'Absolutely Baffled'), ('Ill Informed', 'Ill Informed'), ('Slightly Capable', 'Slightly Capable'), ('Considerably Proficient', 'Considerably Proficient'), ('PhD', 'PhD')], max_length=500, null=True, verbose_name='Overall how would you evaluate yourself over the topics you learned in this track?'),
        ),
    ]
