# Generated by Django 2.1.3 on 2018-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_number', models.CharField(default='DEFAULT', max_length=100)),
                ('p_1', models.CharField(default='DEFAULT', max_length=1000)),
                ('p_2', models.CharField(default='DEFAULT', max_length=1000)),
                ('p_3', models.CharField(default='DEFAULT', max_length=1000)),
            ],
        ),
    ]
