# Generated by Django 2.1.3 on 2018-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_auto_20181201_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='school_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
