# Generated by Django 2.1.3 on 2018-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0003_auto_20181201_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='genie_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='school_number',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='text',
        ),
        migrations.AddField(
            model_name='activity',
            name='g_choice',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='g_name',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='g_whatever',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
