# Generated by Django 2.1.3 on 2018-12-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_auto_20181202_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolNumber',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='g_whatever',
            new_name='honeypot',
        ),
    ]
