# Generated by Django 2.1.3 on 2018-12-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0005_auto_20181202_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='TaskTwoGenie',
        ),
    ]
