# Generated by Django 2.1.3 on 2018-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0007_tasktwocustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktwogenie',
            name='wishes',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
