# Generated by Django 2.1.3 on 2018-12-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0009_auto_20181207_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Levels',
        ),
    ]
